obj-$(CONFIG_SENSORS_SSC)	+= sensors_ssc.o
#Huaqin add for als/ps by zhuqiang at 2018/08/03 start
obj-$(CONFIG_INPUT_STK3335)	+= sensors_class.o stk3x3x/
#Huaqin add for als/ps by zhuqiang at 2018/08/03 end
