#
# for huaqin config distinction by gpio
#

# Huaqin add for ZQL1820-145 by zhaojunhai1 at 2018/08/06 start
obj-$(CONFIG_HQ_CONFIG_DIST) += config_dist.o
# Huaqin add for ZQL1820-145 by zhaojunhai1 at 2018/08/06 end
