#
# for huaqin misc info
#
cflag += -W

# Huaqin add for ZQL1650-86 by liunianliang at 2018/02/09 start
obj-$(CONFIG_HQ_HARDWARE_INFO)   += hardware_info/
# Huaqin add for ZQL1650-86 by liunianliang at 2018/02/09 end

# Huaqin add for ZQL1650-1179 by liunianliang at 2018/04/20 start
obj-$(CONFIG_HQ_SIM_TRAY_CHECK)   += sim_tray/
# Huaqin add for ZQL1650-1179 by liunianliang at 2018/04/20 end

# Huaqin add for ZQL1820-145 by zhaojunhai1 at 2018/08/06 start
obj-$(CONFIG_HQ_CONFIG_DIST)   += config_distinction/
# Huaqin add for ZQL1820-145 by zhaojunhai1 at 2018/08/06 end
